In [1]:
#Import Libraries
import pandas as pd
import numpy as np

In [2]:
#Load the dataset
df = pd.read_csv("C:/Users/Kevin.Moses/Desktop/ICBT Assignments/1. New Batch Assignments/Final Project/Final_Project/data/raw/water_pollution_disease.csv")

In [3]:
#Display First Rows
df.head()

,Country,Region,Year,Water Source Type,Contaminant Level (ppm),pH Level,Turbidity (NTU),Dissolved Oxygen (mg/L),Nitrate Level (mg/L),Lead Concentration (µg/L),...,"Cholera Cases per 100,000 people","Typhoid Cases per 100,000 people","Infant Mortality Rate (per 1,000 live births)",GDP per Capita (USD),Healthcare Access Index (0-100),Urbanization Rate (%),Sanitation Coverage (% of Population),Rainfall (mm per year),Temperature (°C),Population Density (people per km²)
0,Mexico,North,2015,Lake,1.04,6.88,0.15,9.38,10.91,3.03,...,1,4,13.77,11855,59.52,85.96,97.36,676,16.48,80
1,Brazil,West,2017,Well,2.48,7.26,1.06,6.73,21.71,4.67,...,2,5,19.08,10434,80.14,84.78,94.37,1796,23.11,25
2,Indonesia,Central,2022,Pond,3.38,7.58,7.03,4.67,22.55,8.32,...,9,35,35.79,4559,54.05,51.23,76.44,1672,24.76,114
3,Nigeria,East,2016,Well,2.50,6.86,2.40,7.88,16.29,5.01,...,2,8,74.65,2293,46.38,58.27,48.95,1015,25.97,241
4,Mexico,South,2005,Well,0.73,6.52,2.24,7.80,8.91,2.00,...,1,2,18.73,10765,71.50,91.83,87.58,453,25.09,52

In [4]:
#Dataset Shape
print("Dataset Shape:", df.shape)

Dataset Shape: (3000, 24)

In [5]:
#Column Names  
df.columns

Index(['Country', 'Region', 'Year', 'Water Source Type',
       'Contaminant Level (ppm)', 'pH Level', 'Turbidity (NTU)',
       'Dissolved Oxygen (mg/L)', 'Nitrate Level (mg/L)',
       'Lead Concentration (µg/L)', 'Bacteria Count (CFU/mL)',
       'Water Treatment Method', 'Access to Clean Water (% of Population)',
       'Diarrheal Cases per 100,000 people',
       'Cholera Cases per 100,000 people', 'Typhoid Cases per 100,000 people',
       'Infant Mortality Rate (per 1,000 live births)', 'GDP per Capita (USD)',
       'Healthcare Access Index (0-100)', 'Urbanization Rate (%)',
       'Sanitation Coverage (% of Population)', 'Rainfall (mm per year)',
       'Temperature (°C)', 'Population Density (people per km²)'],
      dtype='str')

In [6]:
#Dataset Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Country                                        3000 non-null   str
 1   Region                                         3000 non-null   str
 2   Year                                           3000 non-null   int64
 3   Water Source Type                              3000 non-null   str
 4   Contaminant Level (ppm)                        3000 non-null   float64
 5   pH Level                                       3000 non-null   float64
 6   Turbidity (NTU)                                3000 non-null   float64
 7   Dissolved Oxygen (mg/L)                        3000 non-null   float64
 8   Nitrate Level (mg/L)                           3000 non-null   float64
 9   Lead Concentration (µg/L)                      3000 non-null   float64
 10  Bacteria Count (CFU/mL)                        3000 non-null   int64
 11  Water Treatment Method                         2253 non-null   str
 12  Access to Clean Water (% of Population)        3000 non-null   float64
 13  Diarrheal Cases per 100,000 people             3000 non-null   int64
 14  Cholera Cases per 100,000 people               3000 non-null   int64
 15  Typhoid Cases per 100,000 people               3000 non-null   int64
 16  Infant Mortality Rate (per 1,000 live births)  3000 non-null   float64
 17  GDP per Capita (USD)                           3000 non-null   int64
 18  Healthcare Access Index (0-100)                3000 non-null   float64
 19  Urbanization Rate (%)                          3000 non-null   float64
 20  Sanitation Coverage (% of Population)          3000 non-null   float64
 21  Rainfall (mm per year)                         3000 non-null   int64
 22  Temperature (°C)                               3000 non-null   float64
 23  Population Density (people per km²)            3000 non-null   int64
dtypes: float64(12), int64(8), str(4)
memory usage: 562.6 KB

In [7]:
#Statistical Summary
df.describe()

,Year,Contaminant Level (ppm),pH Level,Turbidity (NTU),Dissolved Oxygen (mg/L),Nitrate Level (mg/L),Lead Concentration (µg/L),Bacteria Count (CFU/mL),Access to Clean Water (% of Population),"Diarrheal Cases per 100,000 people","Cholera Cases per 100,000 people","Typhoid Cases per 100,000 people","Infant Mortality Rate (per 1,000 live births)",GDP per Capita (USD),Healthcare Access Index (0-100),Urbanization Rate (%),Sanitation Coverage (% of Population),Rainfall (mm per year),Temperature (°C),Population Density (people per km²)
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,2012.012667,1.972287,7.043397,2.743283,7.335710,16.950683,4.799220,361.840000,78.223633,92.469333,3.562667,9.113333,37.251260,10251.307000,63.115777,57.502410,72.905567,1276.001000,21.839833,281.549667
std,7.229287,0.961239,0.380709,2.140164,1.054605,5.792659,2.616363,416.813769,14.295192,66.967355,4.203407,8.621171,23.368128,15032.513018,14.495548,21.102243,17.197683,666.430851,5.370643,358.300120
min,2000.000000,0.020000,5.700000,0.150000,3.970000,2.880000,0.050000,2.000000,40.970000,4.000000,0.000000,0.000000,2.000000,958.000000,28.450000,15.000000,28.130000,301.000000,7.040000,12.000000
25%,2006.000000,1.230000,6.790000,1.060000,6.610000,12.737500,2.837500,59.000000,67.877500,41.000000,1.000000,3.000000,16.815000,2217.000000,51.897500,39.647500,63.887500,805.000000,17.877500,64.000000
50%,2012.000000,1.950000,7.050000,2.290000,7.350000,16.400000,4.690000,232.000000,78.285000,77.000000,2.000000,7.000000,32.940000,4128.500000,62.455000,57.160000,75.130000,1044.000000,23.200000,159.000000
75%,2018.000000,2.660000,7.300000,4.010000,8.082500,20.742500,6.652500,512.000000,91.140000,130.000000,5.000000,13.000000,62.345000,10543.000000,73.762500,78.890000,86.762500,1709.000000,26.000000,305.000000
max,2024.000000,5.060000,8.510000,11.430000,10.260000,36.670000,14.200000,3435.000000,99.700000,462.000000,36.000000,58.000000,85.990000,64097.000000,99.000000,96.000000,99.500000,3600.000000,32.660000,1700.000000

In [8]:
#Missing Values
df.isnull().sum()

Country                                            0
Region                                             0
Year                                               0
Water Source Type                                  0
Contaminant Level (ppm)                            0
pH Level                                           0
Turbidity (NTU)                                    0
Dissolved Oxygen (mg/L)                            0
Nitrate Level (mg/L)                               0
Lead Concentration (µg/L)                          0
Bacteria Count (CFU/mL)                            0
Water Treatment Method                           747
Access to Clean Water (% of Population)            0
Diarrheal Cases per 100,000 people                 0
Cholera Cases per 100,000 people                   0
Typhoid Cases per 100,000 people                   0
Infant Mortality Rate (per 1,000 live births)      0
GDP per Capita (USD)                               0
Healthcare Access Index (0-100)                    0
Urbanization Rate (%)                              0
Sanitation Coverage (% of Population)              0
Rainfall (mm per year)                             0
Temperature (°C)                                   0
Population Density (people per km²)                0
dtype: int64

In [9]:
#Duplicate Rows
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [10]:
#Unique Values
df.nunique()

Country                                            10
Region                                              5
Year                                               25
Water Source Type                                   6
Contaminant Level (ppm)                           427
pH Level                                          219
Turbidity (NTU)                                   728
Dissolved Oxygen (mg/L)                           490
Nitrate Level (mg/L)                             1647
Lead Concentration (µg/L)                         958
Bacteria Count (CFU/mL)                          1003
Water Treatment Method                              3
Access to Clean Water (% of Population)          2186
Diarrheal Cases per 100,000 people                301
Cholera Cases per 100,000 people                   32
Typhoid Cases per 100,000 people                   52
Infant Mortality Rate (per 1,000 live births)    2387
GDP per Capita (USD)                             2465
Healthcare Access Index (0-100)                  2277
Urbanization Rate (%)                            2376
Sanitation Coverage (% of Population)            2296
Rainfall (mm per year)                           1539
Temperature (°C)                                 1494
Population Density (people per km²)               766
dtype: int64

In [11]:
#Random Sample
df.sample(10)

,Country,Region,Year,Water Source Type,Contaminant Level (ppm),pH Level,Turbidity (NTU),Dissolved Oxygen (mg/L),Nitrate Level (mg/L),Lead Concentration (µg/L),...,"Cholera Cases per 100,000 people","Typhoid Cases per 100,000 people","Infant Mortality Rate (per 1,000 live births)",GDP per Capita (USD),Healthcare Access Index (0-100),Urbanization Rate (%),Sanitation Coverage (% of Population),Rainfall (mm per year),Temperature (°C),Population Density (people per km²)
2242,Pakistan,North,2006,River,2.24,6.91,2.84,7.83,15.37,4.82,...,14,14,65.18,1634,52.54,38.86,68.19,433,23.69,337
741,Indonesia,Central,2003,Lake,2.70,7.42,2.10,6.60,23.03,5.05,...,2,8,32.61,4555,59.77,64.97,73.02,2938,27.04,127
2885,Mexico,East,2005,Pond,3.70,6.55,7.18,4.93,23.32,8.52,...,4,15,26.52,9476,77.46,72.56,87.95,1012,23.95,40
2786,Indonesia,North,2024,Spring,1.41,7.28,0.89,6.89,19.22,5.26,...,0,3,20.06,5028,64.32,63.83,74.50,2359,29.05,121
803,Ethiopia,East,2010,Well,1.79,7.34,0.15,7.47,9.65,5.62,...,1,4,63.12,1203,42.30,24.74,45.47,841,21.01,124
2205,Nigeria,West,2021,Spring,1.23,6.56,1.84,8.18,14.37,4.70,...,0,7,71.90,2059,45.88,50.22,43.91,1114,27.49,277
1629,Ethiopia,East,2024,Spring,0.02,7.43,0.60,9.59,10.02,3.48,...,0,2,57.29,1291,47.89,26.91,33.61,980,18.25,92
992,Bangladesh,East,2011,Pond,3.13,6.67,4.90,5.01,28.53,9.24,...,14,13,42.37,2883,66.22,32.51,65.71,2320,27.28,1690
2532,Mexico,Central,2022,River,3.24,6.46,5.54,5.73,18.06,8.87,...,8,22,19.89,10275,67.12,91.34,88.97,668,22.65,65
2258,Bangladesh,West,2011,Well,2.53,6.76,4.32,6.96,28.22,5.32,...,8,7,38.21,3156,50.41,43.18,71.53,3123,21.51,1025